storage:
  directory: "url-shortener"
  userLinksFile: "user-links.json"
  activeUsersFile: "active_users.txt"

urlShortener:
  baseUrl: "clck.ru/"
  defaultTtlHours: 24
  codeLength: 6
  alphabet: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

ttlService:
  cleanupIntervalMinutes: 60

